---
# Ansible role for running rally verify (e.g., tempest)

- name: run tempest tests as rally verifier
  shell: "source {{ rally_home }}/bin/activate && rally verify start --pattern set={{ tempest_suite }}"
  args:
    executable: /bin/bash
  notify:
    - generate rally verify report
    - fetch rally verify report
  register: tempest

- debug:
    var: tempest.stdout_lines

...
