---
# Ansible role for running rally verify (e.g., tempest)

- name: activate rally virtual environment 
  command: source /home/rally/rally/bin/activate

- name: list all verifications
  command: rally verify list

- name: run tempest verifier tests
  command: rally verify start --pattern set={{ tempest_suite }}
  notify:
    - generate rally verify report

...
