---
# handlers for rally task command

- name: generate rally task report
  shell: "source {{ rally_home }}/bin/activate && rally task report --html-static --out=./rally-task-report.html"
  args:
    executable: /bin/bash

- name: fetch rally task report
  fetch:
    src: rally-task-report.html
    dest: ./
    flat: yes

...
