# full, smoke, compute, identity, image, network, object_storage, orchestration, volume, scenario
tempest_suite: smoke

# rally installation dir
#rally_home: /home/rally/rally
rally_home: /home/ubuntu/rally
